
root: /

Home: /
About: /about

language: es

author:
description:

favicon: /favicon.ico

github: http://github.com/Amaury-Tobias
twitter: https://twitter.com/Amaury_Tobias
mail: mailto:amaury.tobiasqr@gmail.com
mastodon: https://mstdn.mx/@amaury_tobias

disqus:
  enabled: true
  shortname: amaurytq